version: '3.1'

services:

  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: proot
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: puser
    ports:
      - 20000:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: