/*
 * This file is generated by jOOQ.
 */
package com.ppretki.infrastructure.jooq;


import com.ppretki.infrastructure.jooq.tables.EntityWithArea;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ENTITY_WITH_AREA_AREA = Internal.createIndex(DSL.name("area"), EntityWithArea.ENTITY_WITH_AREA, new OrderField[] { EntityWithArea.ENTITY_WITH_AREA.AREA }, false);
}
