/*
 * This file is generated by jOOQ.
 */
package com.ppretki.infrastructure.jooq;


import com.ppretki.infrastructure.jooq.tables.EntityWithArea;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.ENTITY_WITH_AREA</code>.
     */
    public static final EntityWithArea ENTITY_WITH_AREA = EntityWithArea.ENTITY_WITH_AREA;
}
