/*
 * This file is generated by jOOQ.
 */
package com.ppretki.infrastructure.jooq;


import com.ppretki.infrastructure.jooq.tables.EntityWithArea;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.ENTITY_WITH_AREA</code>.
     */
    public final EntityWithArea ENTITY_WITH_AREA = EntityWithArea.ENTITY_WITH_AREA;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EntityWithArea.ENTITY_WITH_AREA
        );
    }
}
